# Generated by Django 2.0.1 on 2019-06-16 17:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='following',
            field=models.ManyToManyField(related_name='followed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
