# Generated by Django 2.0.1 on 2019-06-17 05:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190616_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
