# Generated by Django 2.0.1 on 2019-06-17 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190617_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='following',
        ),
    ]
